name: Publish

# Run when a new release is... released
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Use checkout to publish the files in your repo
      - name: Remove .github folder
        run: rm -rf .github
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0
          filter: tree:0

      - uses: dhkatz/thunderstore-publish@v1
        id: publish
        with:
          token: ${{ secrets.THUNDERSTORE_SERVICE_KEY }}
          namespace: LethalBreakroom # the thunderstore 'team' to publish under
          name: Lethal_Breakroom_ModPack # the name of the package
          description: Publishes the Lethal Breakroom ModPack to Thunderstore
          ersion: ${{ github.event.release.tag_name }}
          community: repo
          categories: | # <-- notice this pipe character
            modpacks

      - name: Output URL
        run: echo "Published Thunderstore package to ${{ steps.publish.outputs.url }}"
