name: Publish

# Run when a new release is published
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0
          filter: tree:0

      # Publish to Thunderstore
      - uses: dhkatz/thunderstore-publish@v1
        id: publish
        with:
          token: ${{ secrets.THUNDERSTORE_SERVICE_KEY }}
          namespace: LethalBreakroom
          name: Lethal_Breakroom_ModPack
          description: Publishes the Lethal Breakroom ModPack to Thunderstore
          version: ${{ github.event.release.tag_name }}
          communities: repo
          categories: |
            modpacks

      # Output the URL of the published package
      - name: Output URL
        run: echo "Published Thunderstore package to ${{ steps.publish.outputs.url }}"
