name: Publish Mod

# Run when a new release is... released
on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Use checkout to publish the files in your repo
      - uses: actions/checkout@v3
      - uses: GreenTF/upload-thunderstore-package@v4.3
        with:
          namespace: LethalBreakroom # the thunderstore 'team' to publish under
          description: Publishes the Lethal Breakroom ModPack to Thunderstore
          token: ${{ secrets.THUNDERSTORE_SERVICE_KEY }}
          name: Lethal_Breakroom_ModPack # the name of the package
          version: ${{ github.ref_name }} # Use the tag as the package version
          community: repo
          categories: | # <-- notice this pipe character
            modpacks
